package com.zwy.mapper;

import com.zwy.model.Notification;
import org.apache.ibatis.annotations.*;

import java.util.List;
@Mapper
public interface NotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Mon Feb 01 13:25:11 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Mon Feb 01 13:25:11 CST 2021
     */
    @Insert("insert into notification ( notifier, receiver, outerId, type, gmt_create, status) " +
            "values (#{notifier} ,#{receiver}, #{outerId},#{type},#{gmtCreate},#{status})")
    int insert(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Mon Feb 01 13:25:11 CST 2021
     */
    Notification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Mon Feb 01 13:25:11 CST 2021
     */
    List<Notification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Mon Feb 01 13:25:11 CST 2021
     */
    int updateByPrimaryKey(Notification record);

    @Select("select * from notification where receiver = #{userId} order by gmt_create desc limit #{offset},#{size} ")
    List<Notification> listByCreator(@Param(value = "userId") Long userId,
                                                      @Param(value = "offset") Integer offset, @Param(value = "size") Integer size);

    @Select("select count(1) from notification where notifier = #{userId}")
    Integer countByCreator(Long userId);

    @Update("update notification set status = 1  where  id = #{nId} ")
    void read(Long nId);

    @Select("select count(1) from notification where receiver = #{id} and status = 0")
    Integer countUnRead(Long id);
}
